server:
  http_listen_port: 9080
  grpc_listen_port: 0
  graceful_shutdown_timeout: 5s

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki.local/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
      - labels:
          stream:
      - output:
          source: output

  - job_name: application_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: application
          app: myapp
          __path__: /var/log/app/*.log
    pipeline_stages:
      - match:
          selector: '{job="application"}'
          stages:
            - regex:
                expression: '(?P<level>(INFO|DEBUG|WARN|ERROR)) (?P<message>.*)'
            - labels:
                level:

limits_config:
  readline_rate_limit: 10M
  readline_burst_limit: 15M

target_config:
  sync_period: 10s
